[master_config]
hostname = "127.0.0.1"
port = 8080

[[slave_config]]
hostname="127.0.0.1"
port=8081

[[slave_config]]
hostname="127.0.0.1"
port=8082

[[slave_config]]
hostname="127.0.0.1"
port=8083

[[slave_config]]
hostname="127.0.0.1"
port=8084
